name: Event and Release

on:
  release:
    types: 
      - 'created'
  push:
    branches:
      - 'master'

jobs:
  event-job:
    runs-on: ubuntu-latest
    steps:
      - name: Event
        run: echo ${{ github.ref_name }}

      - name: Release
        if: github.event_name == 'release' && github.event.action == 'created'
        run: echo ${{ github.ref_name }}
