name: Event

on:
  release:
    types: 
      - 'created'
  push:
    branches:
      - 'master'

jobs:
  event-job:
    runs-on: ubuntu-latest
    steps:
      - name: Event
        run: echo Hello

  release-job:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - name: Event
        run: echo World
